import * as yup from "yup";

export const InitialValues = {
  referredCode: "",
  riderTypeId: "",
  firstName: "",
  lastName: "",
  mobileNumber: "",
  riderStartDate: "",
  email: "",
  vehicleTypeId: "",
  batchLevelId: "",
  bagTypeId: "",
  image: "",
  nidFront: "",
  nidBack: "",
  mac: "",
  imei: "",
  bkashNo: "",
  nagadNo: "",
  cityId: "",
  electricityBill: "",
  guardianNidFront: "",
  guardianNidBack: "",
  houseNameplate: "",
  isApprove: false,
  permanentAddress: "",
  presentAddress: "",
  deviceId: "",
  birthDate: "",
  drivingLicenseId: "",
  drivingLicenseImage: "",
  nidNo: "",
  referrerUrl: "",
  vehicleRegistrationId: "",
  vehicleRegistrationImage: "",
};

export const RiderSchema = yup.object({
  firstName: yup.string().required("This field is required"),
  lastName: yup.string().required("This field is required"),
  mobileNumber: yup.number().positive().required("This field is required"),
  batchLevelId: yup.string().required("This field is required"),
  bagTypeId: yup.string().required("This field is required"),
  email: yup.string(),
  birthDate: yup.date().required("This field is required"),
  image: yup.mixed(),
  nidNo: yup.number().positive().required("This field is required"),
  nidFront: yup.mixed().required("This field is required"),
  nidBack: yup.mixed().required("This field is required"),
  mac: yup.string(),
  imei: yup.string(),
  bkashNo: yup.number().positive(),
  nagadNo: yup.number().positive(),
  drivingLicenseId: yup.string(),
  drivingLicenseImage: yup.mixed(),
  vehicleRegistrationId: yup.string(),
  vehicleRegistrationImage: yup.mixed(),
  presentAddress: yup.string().required("This field is required"),
  permanentAddress: yup.string(),
  vehicleTypeId: yup.number().required("This field is required"),
  cityId: yup.number().required("This field is required"),
  guardianNidFront: yup.mixed(),
  guardianNidBack: yup.mixed(),
  electricityBill: yup.mixed(),
  houseNameplate: yup.mixed(),
});
